version: 1.0.{build}
image: Visual Studio 2019
configuration: Release

branches:
  only:
    - master

install:
- ps: >-
    cd src

    nuget restore Vortice.sln

    $env:VORTICE_BUILD_NUMBER = ([int]$env:APPVEYOR_BUILD_NUMBER).ToString("000")
   
    $env:VORTICE_VERSION_SUFFIX = "pre$env:VORTICE_BUILD_NUMBER"

    $env:appveyor_nuget_push = 'false'

    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      if($env:appveyor_repo_tag -eq 'True') {
    	  if($env:appveyor_repo_tag_name -match '^v[0-9]') {
           $env:appveyor_nuget_push = 'true'
           $env:VORTICE_VERSION_SUFFIX = ""
        }
    	  if($env:appveyor_repo_tag_name -eq 'latest') {
           $env:appveyor_nuget_push = 'true'
        }        
      }
    }

build:
  project: src/Vortice.sln
  verbosity: minimal

before_package:
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release core/Vortice/Vortice.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release engine/Vortice.Graphics/Vortice.Graphics.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release engine/Vortice.Graphics.Direct3D11/Vortice.Graphics.Direct3D11.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release engine/Vortice.Graphics.Direct3D12/Vortice.Graphics.Direct3D12.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release engine/Vortice.Audio/Vortice.Audio.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release engine/Vortice.Game/Vortice.Game.csproj

artifacts:
- path: bin\Packages\Release\*.nupkg
  name: Nugets Artifacts

nuget:
  project_feed: true

deploy:
- provider: NuGet
  api_key:
    secure: 7kKL2l4dDfYB1nulVfUJYAtx43lETKMX+fMrnOwO9wljBNXanlMubrTSjgpaWnzn
  on:
    appveyor_nuget_push: true
  artifact: Nugets Artifacts 
